Repository elastic/package-spec, pull requests merged in 2022-07, with the labels that each got.

#366 Add threat_intel package category
  versions/1/changelog.yml
  versions/1/integration/manifest.spec.yml
Labels: Team:Ecosystem

#307 Add transform to spec
  test/packages/good/elasticsearch/transform/good_example_abc_1/transform.yml
  test/packages/good/elasticsearch/transform/good_example_bdc_2/manifest.yml
  test/packages/good/elasticsearch/transform/good_example_bdc_2/transform.yml
  test/packages/good/elasticsearch/transform/metadata_current/fields/fields.yml
  test/packages/good/elasticsearch/transform/metadata_current/manifest.yml
  test/packages/good/elasticsearch/transform/metadata_current/transform.yml
  test/packages/good/elasticsearch/transform/metadata_united/fields/fields.yml
  test/packages/good/elasticsearch/transform/metadata_united/manifest.yml
  test/packages/good/elasticsearch/transform/metadata_united/transform.yml
  versions/1/changelog.yml
  versions/1/integration/elasticsearch/spec.yml
  versions/1/integration/elasticsearch/transform/manifest.spec.yml
  versions/1/integration/elasticsearch/transform/spec.yml
  versions/1/integration/elasticsearch/transform/transform.spec.yml
Labels: Team: csp

#356 Add textarea var type
  versions/1/changelog.yml
  versions/1/integration/data_stream/manifest.spec.yml
Labels: discuss

#377 ci: report test results and coverage in the CI
  .ci/Jenkinsfile
  .gitignore
  Makefile
  code/go/Makefile
  go.mod
  go.sum
Labels: automation, Team:Automation

#378 Add support for icons in dark mode
  code/go/pkg/validator/validator_test.go
  test/packages/icons_dark_mode/NOTICE.txt
  test/packages/icons_dark_mode/_dev/build/build.yml
  test/packages/icons_dark_mode/_dev/build/docs/README.md
  test/packages/icons_dark_mode/changelog.yml
  test/packages/icons_dark_mode/docs/README.md
  test/packages/icons_dark_mode/img/system-dark.svg
  test/packages/icons_dark_mode/img/system.svg
  test/packages/icons_dark_mode/manifest.yml
  versions/1/changelog.yml
  versions/1/integration/manifest.spec.yml
Labels: Team:Ecosystem
